### ISSUE TITLE
NullPointerException - SQL Server permission problem 

### ISSUE THREAD

**Issue by MartinR4838** [sfa-siard/SiardGui#11]
NullPointerException encountered on SQL Server 2012 express - DB size (bak file) ~ 6,6 GB, File storage in DB as BLOB.

Error is produced when user has only db_datareader role (as requests manual Introduction point 2.). User must be in db_dataowner role and than all runs.

**Comment by HartwigThomas** [comment]
I could not reproduce the error. Which version of SIARD is being used. Where in the manual is the role specified?

**Comment by MartinR4838** [comment]
I was using version 2.1.112 and same NullPointerException with v. 2.1.127. Manual part Introduction to Database Archival, 2. 
" Prepare the database for archival: create a new user on the database system that only has read permissions to objects that need to be archived. If needed, create a copy of your database (or certain tables/parts of it) or create views. The database may not be changed during the archival process, otherwise extraction with SIARD Suite will fail. Never archive from a live system.
Download the database using SIARD Suite.
![cutSSMS1](https://user-images.githubusercontent.com/54624927/72359522-b5e4ab80-36ee-11ea-94fb-185ab21dfb30.JPG)
![cut_suite21112](https://user-images.githubusercontent.com/54624927/72359523-b5e4ab80-36ee-11ea-912a-f4d5fb19f93e.JPG)

**Comment by HartwigThomas** [comment]
I tried to reproduce the problem and did not succeed.
My "archiv" login has the role "public" and is mapped to user "buguser" of database "bugdb".
"buguser" only has the role "db_datareader" and is not the owner of "bugdb" (only has "Connect" permission from the database).
When I use SIARD to connect to "bugdb" with login "archiv", I can download the database without any problems.
Thus the remark in the manual still seems correct to me.

In order to understand your observation better and to be able to reproduce it, I should need more information about Login/User/Database permissions and roles.

**Comment by MartinR4838** [comment]
Dear Mr. Hartwig, you are very kind and I appreciate it. I have opened this issue on your request but it is not a real problem for me. Suite is working fine and I´m using SQL server just for tests to deploy SIARD packages. It is apparently hidden somewhere in options/permission/roles of my server and it seems useless to look for it.  I will close issue if you agree. Thanks!

**Comment by HartwigThomas** [comment]
OK
