### ISSUE TITLE
Siardgui.cmd and siardgui.ps1 seems to try to open the siardgui.jar file in the wrong place

### ISSUE THREAD

**Issue by Tarjei-stavanger** [sfa-siard/SiardGui#24]
It appears that the programs have not been tested when they are located in the .\bin directory.

Command : bin\siardgui.cmd

It still tries to open the siardgui.jar file in the bin\lib directory.

Incidentally, there is no siardgui.jar file in the distribution at all. So I think there is reason to question the testing of the distribution.

**Comment by HartwigThomas** [comment]
There is no ./bin directory in the distribution.
siardgui.cmd is located in the root folder of the distribution (release).
it references siardgui.jar in the ./lib folder of the distribution (release).
A siardgui.jar is located in the ./lib folder of the distribution.

There _exists_ a ./bin directory in the developer's source tree.
And of course, the developer's source tree does not contain a siardgui.jar, because that is created by the build and is not part of the "sources".
However, the build creates the siardgui.jar and packages all files in the distribution.
