### ISSUE TITLE
SIARD fails in MySQL 8.0 with the error: Table columns_priv has no columns!

### ISSUE THREAD

**Issue by tsaixingwei** [sfa-siard/SiardGui#52]
Running SiardGui version 2.2.11 on a very simple MySQL 8.0 database on Windows 11. The table only has two user-defined tables of only 3 columns each. 

But SiardGui executes the downloading of the database, the error given is:

> Database download failed (  java.sql.SQLException: Table columns_priv has no columns!)! Partial download is deleted.

I queried the database for the table mysql.columns_priv (this is a system grant table in MySQL) and it exists and has multiple columns. So this can't be the real cause. 

I tried this again multiple other MySQL databases and the same error occurred.

![Screenshot 2023-04-02 095913](https://user-images.githubusercontent.com/15616346/229334856-ae7bdf4a-5d96-4b51-9d2e-18d899742e01.png)

**Comment by mburri** [comment]
@tsaixingwei 
Thank you for your error report.

Do you use the root user to archive your database?

It's generally adviced to create a dedicated user and grant this user access rights to the schema/database that you actually want to archive. Otherwise all schemas, tables and data the root user has grants on are archived. That is usually not what you want.

I think using another user should fix your problem.

It should nonetheless be possible to export your database using the root user and we will look into this. But it will take some time for us to address this issue.

**Comment by tsaixingwei** [comment]
I used root but also another user account named “user” for lack of an
imagination 😊
Both had the same problem

Yahya

**Comment by mburri** [comment]
We noticed that this issue affects mysql versions since Version 8. However connecting to MySql 5.x seems to be broken too...

Maria DB supports seems to be better.

**Comment by sdbuehlmann** [comment]
Duplicate (see https://github.com/sfa-siard/JdbcMySql/issues/4).
